### PR TITLE
Feature bookmarkable filter enhancement

### PR DESCRIPTION
**Pull request by RetGal**
Includes all changes requested in #214, except 10.

### CODE REVIEW

**Comment by yvespp** [comment]
Can you please change failure reason "timeout failed" to just "timeout"?

**Comment by yvespp** [comment]
Maybe use "glyphicon glyphicon-repeat" instead of "glyphicon glyphicon-flash" for the redeploy action?

**Comment by yvespp** [comment]
We could move stuff more to left now that the border is gone an there is now sidebar:
image

**Comment by yvespp** [comment]
When I delete all Deployment filters the "Apply filter" button is deactivated. I think it should now be always active now that we show the last 10 deployment by default.

**Comment by yvespp** [comment]
Clicking on the App server link takes me to the wrong AppServer. The id that is passed seams to be wrong.

**Comment by RetGal** [comment]
@yvespp All done

**Comment by yvespp** [comment]
Thanks!
Found an new one: pagination doesn't work with "Latest deployment job for App Server and Env" filter

**Pull request merged**
