### PR TITLE
Feature editable identifier for resource relation entities

### PR DESCRIPTION
**Pull request by RetGal**
As requested

### CODE REVIEW

**Comment by yvespp** [comment]
@RetGal now it has merge conflicts :-(

**Comment by yvespp** [comment]
Maybe we should merge 1.12 into master first? But 1.12 pull has merge conflicts as well.

**Comment by RetGal** [comment]
Yes, this solved these conflicts as well

**Comment by yvespp** [comment]
I installed and tested the branch. Here are my findings:
* I can't use the identifier in templates, I test with a test mydb:
sample

I tried the following template:
```
db=${mydb.jndiName}
db=${testdb.jndiName} -> doesn't work
db=${mydb_testdb.jndiName} -> doesn't work
db=${mydb_1.jndiName}
```
I noticed that when you added the same resource twice, the generated Identifier is set to 1, but in the templates you have to use mydb_1 to access it. You can see this in the screenshot above.

* On resource type the identifier is called RelationName. Maybe we should also call it RelationName here?
* If I change the Identifier to a name that already exists, one relation disappears. We should validate that the name is not already taken before changing it.

**Comment by yvespp** [comment]
@RetGal the identifiert is editable on all environments. Can you please make it only editable on Global, like name?

**Comment by yvespp** [comment]
In the rest interface (e.g. GET /resources/{resourceGroupName}/{releaseName}/relations) it is still called identifier, we should also rename it to RelationName.

**Comment by yvespp** [comment]
I can't add a new relation to a resource, if there is not already a relation to that resource type. Error in log: 
```
2017-07-11 16:12:13,257 logLev=SEVERE class=AMWExceptionHandler thread="ajp-/0.0.0.0:8009-1" An Error occured: javax.faces.FacesException: /resources/mobi/addRelation.xhtml @147,127 listener="#{relationDataProvider.addConsumedResource(selectableItem.id)}": java.lang.NullPointerException
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:89)
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:295)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at ch.puzzle.itc.mobiliar.presentation.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:43)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at ch.puzzle.itc.mobiliar.presentation.util.CachingFilter.doFilter(CachingFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:246)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:214)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:231)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:149)
        at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.event(JBossWebContext.java:91)
        at org.jboss.modcluster.container.jbossweb.JBossWebContext$RequestListenerValve.invoke(JBossWebContext.java:72)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:512)
        at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
        at org.jboss.as.jpa.interceptor.WebNonTxEmCloserValve.invoke(WebNonTxEmCloserValve.java:50)
        at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:169)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:151)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:97)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:102)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:490)
        at org.apache.coyote.ajp.AjpProtocol$AjpConnectionHandler.process(AjpProtocol.java:422)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:926)
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_111]
Caused by: javax.el.ELException: /resources/mobi/addRelation.xhtml @147,127 listener="#{relationDataProvider.addConsumedResource(selectableItem.id)}": java.lang.NullPointerException
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:111)
        at org.ajax4jsf.component.behavior.MethodExpressionAjaxBehaviorListener.processAjaxBehavior(MethodExpressionAjaxBehaviorListener.java:69)
        at javax.faces.event.AjaxBehaviorEvent.processListener(AjaxBehaviorEvent.java:113)
        at javax.faces.component.behavior.BehaviorBase.broadcast(BehaviorBase.java:106)
        at org.ajax4jsf.component.behavior.AjaxBehavior.broadcast(AjaxBehavior.java:393)
        at javax.faces.component.UIComponentBase.broadcast(UIComponentBase.java:762)
        at javax.faces.component.UICommand.broadcast(UICommand.java:300)
        at javax.faces.component.UIData.broadcast(UIData.java:1106)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
        ... 27 more
Caused by: java.lang.NullPointerException
        at ch.puzzle.itc.mobiliar.presentation.propertyEdit.RelationDataProvider.addConsumedResource(RelationDataProvider.java:312)
        at ch.puzzle.itc.mobiliar.presentation.propertyEdit.RelationDataProvider$Proxy$_$$_WeldClientProxy.addConsumedResource(RelationDataProvider$Proxy$_$$_WeldClientProxy.java)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_111]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:258)
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:278)
        at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
        at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
        ... 37 more
```

**Comment by yvespp** [comment]
I can still add relations with the same name:
1. Add a relation to resource that already has a relation. The first RelationName is empty, the second RelationName  is postfixed with _1 (e.g. adIntern and adIntern_1)
2. Set the RelationName of the second relation to the the name of the releated resource (e.g. adIntern).

=> one relation disappears.

**Comment by yvespp** [comment]
@RetGal https://github.com/liimaorg/liima/pull/114#issuecomment-314457388 is still open and Travis has a problem. Can you take another look please?

**Pull request closed without merging**
