### PR TITLE
wip: switch to angular cli and angular 8

### PR DESCRIPTION
**Pull request by yvespp**
Ref: #508 
Here is my try to switch to the angular cli. I followed this guide mostly: <https://www.codepedia.org/ama/fast-faster-angular-cli-how-i-converted-my-angular-project-to-use-angular-cli>
I started by just trying to to run the app and fix everything that came up. I threw out pretty much all the config and added it back when something was broken.
The app compiles now and shows something in the browser.

Done:
* migrate service to new rxjs
* switch to new angular httpclient

Todo as far as i can see:
- [x] I remove angular2 table and replaced it quickly with a plain table, the filter was removed
- [x] fix catch after flatmap in permission.servie.ts:74
- [x] set the baseUrl
- [x] make tests work
- [x] test
- [x] update maven config
- [x] change frontend-maven-plugin:1.6:yarn to npm/ng ?

### CODE REVIEW

**Comment by yvespp** [comment]
@lackrobin once everything works and the all the tests pass we can merge it, not before.
I was hopping you guys could fix the most of it in this branch. I don't have a lot of Node/JavaScript experience and it takes me long to figure out how to fix stuff.

**Comment by lackrobin** [comment]
@yvespp Oh, sorry I missunderstood. Me and @sdedijer are working on this together, but our frontend skills are also limited. We'll do what we can, and hope for some input from Max once he is back.

**Comment by mburri** [comment]
I fixed the runtime exceptions on the deployments page - not sure what is still open now and what items from the checklist needs some more work.

@yvespp 
Can you elaborate on the follwoing items:
* "I remove angular2 table and replaced it quickly with a plain table, the filter was removed"
What does this mean? what needs to be done?

* "set the baseUrl"
of what? theres a baseUrl defined in base.service.ts - that all other Services depend on. Needs this to be fixed or what is the issue here?

**Comment by yvespp** [comment]
@mburri 
> * "I remove angular2 table and replaced it quickly with a plain table, the filter was removed"
>   What does this mean? what needs to be done?

I mean my changes I did to the auditview component: https://github.com/liimaorg/liima/pull/512/files#diff-b59fad1b5d12e982ae4e848119a1c1e1

I removed the DataTableModule and all the filters. They have to be reimplemented and I'm not even sure if the view works at all...

> * "set the baseUrl"
>   of what? theres a baseUrl defined in base.service.ts - that all other Services depend on. Needs this to be fixed or what is the issue here?

I guess this is done then, I saw a lot of errors in the javascript console back then...

Do tests work now? Travis CI ist green, are the test run?

**Comment by yvespp** [comment]
Also maybe we should update more npm modules, from the last Travis build log:
```
[INFO] found 9 vulnerabilities (1 moderate, 8 high)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
```

It seems test aren't run in Travis yet.

**Comment by lackrobin** [comment]
Tests are not working yet

**Comment by mburri** [comment]
The table in auditview is fixed now (sortable and searchable with highlighting the resutls)

**Comment by mburri** [comment]
@Yvesp 
the tests complete sucessfully now.
could you do some manual tests since we don't know the application in detail.
My first tests show that the permission management (http://localhost:4200/#/permission/user) looks odd and i am not able to open the audit view from within the application.
is this inentional or did i just miss the link?

**Comment by mburri** [comment]
This could be merged from my perspective...

**Comment by yvespp** [comment]
I will test early next week, thanks!

**Comment by yvespp** [comment]
From build log https://travis-ci.org/liimaorg/liima/builds/643886635#L1354
```
[INFO] found 1 high severity vulnerability
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
```
Can you check that please?

**Comment by yvespp** [comment]
I tried with the master docker image and there seems to be a problem with the path of the angular gui. In the old version the path was `/AMW_angular/#/deployments` but now it is `/AMW_angular/liima/#/deployments`. Can you witch it back to the old path?

**Comment by mburri** [comment]
I'm am not aware of any changes we made in that direction but I'll have a look.

**Comment by mburri** [comment]
I just built the docker image locally:

```
mvn clean install
AMW_docker/build.sh
```
and started it with docker-compose:

`docker-compose -f ./AMW_docker/docker-compose/docker-compose.yml up -d`

The angular frontend is available at http://localhost:8080/AMW_angular/#/deployments

Is your master docker image a different one?

**Comment by mburri** [comment]
regarding the security issue:

```
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bootstrap-tagsinput                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bootstrap-tagsinput                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bootstrap-tagsinput                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/124                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by yvespp** [comment]
The layout of some screen is different now, stuff like text and icons are closer together. Can this be fixed?

Permissions
Old
image

New:
image

Deployment:
Old:
image

New:
image

**Comment by yvespp** [comment]
> I just built the docker image locally:
> 
> ```
> mvn clean install
> AMW_docker/build.sh
> ```
> 
> and started it with docker-compose:
> 
> `docker-compose -f ./AMW_docker/docker-compose/docker-compose.yml up -d`
> 
> The angular frontend is available at http://localhost:8080/AMW_angular/#/deployments
> 
> Is your master docker image a different one?

I used the one from dockerhub: docker run -i -p 8080:8080 liimaorg/liima:master

**Comment by yvespp** [comment]
The tab title is strange too, the right tab is the old version:
image

**Comment by yvespp** [comment]
Adding an Application server filter gives an error:
image

It seems that the parameter is missing, the old versions uses this call:
```
https://liima.mobicorp.ch/AMW_rest/resources/deployments/filterOptionValues/?filterName=Application%20server
```

**Comment by yvespp** [comment]
The deployment button doesn't active when create a deployment and deploying isn't possible:
image

**Comment by mburri** [comment]
> The tab title is strange too, the right tab is the old version:
> image
@yvespp 
The tab title was configured in webpack.common.js - this file does not exist anymore. Is there a need for the title to be set at build time or could we just hard code it to "Liima"?

**Comment by yvespp** [comment]
> > The tab title was configured in webpack.common.js - this file does not exist anymore. Is there a need for the title to be set at build time or could we just hard code it to "Liima"?

Hard coding is fine

**Comment by mburri** [comment]
@yvespp 
I fixed the reported issues and also made the upgrade to angular9 
Could you do some more tests, please?

**Comment by yvespp** [comment]
When trying to edit a deployment a get this error in the js console:
```
core.js:5828 ERROR TypeError: Tw(...).modal is not a function
    at m._complete (deployments.component.ts:239)
    at m.t (Subscriber.js:166)
    at m.__tryOrUnsub (Subscriber.js:183)
    at m.complete (Subscriber.js:168)
    at f._complete (Subscriber.js:79)
    at f.complete (Subscriber.js:61)
    at Q_._complete (Subscriber.js:79)
    at Q_.complete (Subscriber.js:61)
    at N._complete (Subscriber.js:79)
    at N.complete (Subscriber.js:61)
```
To reproduce you have to create a deployment with a future deployment date, the select deployment and when you hit edit, the error above is logged.

**Comment by yvespp** [comment]
The deployment angular screen logs this when I open it:
```
timer.js:4 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at timer.js:4
    at timer.js:111
```
Can you have a look if this is a problem?

**Comment by yvespp** [comment]
The button and icon spacing is not fixed yet:

New:
image

Old:
image

**Comment by yvespp** [comment]
The export button shows `Error retrieving your data` and in the JS log shows this:
```
Om {headers: wm, status: 200, statusText: "OK", url: "http://localhost:8080/AMW_rest/…%5D&colToSort=d.deploymentDate&sortDirection=DESC", ok: false, …}
headers: wm {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
status: 200
statusText: "OK"
url: "http://localhost:8080/AMW_rest/resources/deployments/filter?filters=%5B%5D&colToSort=d.deploymentDate&sortDirection=DESC"
ok: false
name: "HttpErrorResponse"
message: "Http failure during parsing for http://localhost:8080/AMW_rest/resources/deployments/filter?filters=%5B%5D&colToSort=d.deploymentDate&sortDirection=DESC"
error:
error: SyntaxError: Unexpected token I in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.o (http://localhost:8080/AMW_angular/main-es2015.f1ea1d5a0dd9ef5ee9d1.js:1:835728) at l.invokeTask (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:7919) at Object.onInvokeTask (http://localhost:8080/AMW_angular/main-es2015.f1ea1d5a0dd9ef5ee9d1.js:1:658769) at l.invokeTask (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:7840) at i.runTask (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:3328) at u.invokeTask [as invoke] (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:8969) at p (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:20922) at XMLHttpRequest.f (http://localhost:8080/AMW_angular/polyfills-es2015.85192bc3d2937fbf373e.js:1:21246)
text: "Id;Tracking Id;Deployment state;Build success;Deployment executed;App server;Applications;Deployment release;Environment;Target platform;Deployment parameters;Creation date;Request user;Deployment date;Configuration to deploy;Deployment confirmed;Confirmation date;Confirmation user;Cancel date;Cancel user;Status message;↵81107;68942;"scheduled";"true";"false";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"asdf asdf↵asdddd asdfasdf↵fffdd ffdd";"2020-02-12 16:31";"admin";"2020-02-13 16:31";"2020-02-12 16:31";"true";"2020-02-12 16:31";"admin";;;;↵81106;68941;"scheduled";"true";"false";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"";"2020-02-12 16:31";"admin";"2020-02-13 16:31";"2020-02-12 16:31";"true";"2020-02-12 16:31";"admin";;;;↵81105;68940;"canceled";"true";"true";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"";"2020-02-12 16:30";"admin";"2020-02-12 16:31";"2020-02-12 16:30";"true";"2020-02-12 16:30";"admin";"2020-02-12 16:30";"admin";"Deployment canceled at Wed Feb 12 16:30:39 UTC 2020";↵81104;68939;"pre_deploy";"true";"false";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"";"2020-02-12 16:29";"admin";"2020-02-12 16:30";"2020-02-12 16:29";"true";"2020-02-12 16:29";"admin";;;;↵81103;68938;"pre_deploy";"true";"false";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"";"2020-02-12 16:29";"admin";"2020-02-12 16:29";;"true";"2020-02-12 16:29";"admin";;;;↵81102;68937;"failed";"true";"true";"testapplicationserver";"testapplication ";"future";"D";"eap_70";"";"2020-02-12 16:28";"admin";"2020-02-12 16:28";"2020-02-12 16:28";"true";"2020-02-12 16:28";"admin";;;"Predeployment failure at Wed Feb 12 16:28:58 UTC 2020. Reasons: No nodes enabled";↵"
__proto__: Object
```
Looks like it tries to parse the returned CSV as JSON. The browser shoud just download the file.

**Comment by mburri** [comment]
@Yvesp 
could you please test again?

**Comment by mburri** [comment]
@yvespp 
I discovered a portion in the permission component that I don't understand.
The active Route is checked for parameters "actingUser" and "restrictionType" - I'm not sure what this should do and I think it's broken... could you please check this.

**Comment by yvespp** [comment]
* CSV export works
* Deployment edit works
* Permissions works

* `actingUser` seems to work, it's part of the permission delegation feature: #74 and #303. The rout get's called from the edit resource jsf page, there is a screenshot in #303. 
* I think `restrictionType` is to switch between user and role permissions: 
image
  * seems to work as expected...
* Audit view doesn't open because there is exception from java, I think this is caused by the h2 db and isn't a Angular problem. I will check with oracle.

So I think this is good to go or is there something left open?

**Comment by mburri** [comment]
ok - I created a new branch in order to explore some posibilties to refactor the application - but i'd be happy if we could finally close this...

**Pull request merged**
