### PR TITLE
546 no restrictive csp

### PR DESCRIPTION
**Pull request by StephGit**
With this pull request, a stronger CSP is established. With this CSP all JSF-Script-blocks get a unique nonce per response or are whitelisted through a hash. Frame-Anchestors and Base-Uri directives are specified.

The CSP is in Report-Only mode. Before merging it should be removed to enforce the CSP.

### CODE REVIEW

**Comment by yvespp** [comment]
While testing I found some reports of blocked stuff:

/AMW_web/pages/settings.xhtml?mode=releases -> add/edit: 
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-WKFc+4eT4QW4fWj0egeZ3gCD0WV8CEUmYjqf5+sWJ6U=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-w1Dn2viiutwOn5SQ/cg5/cZXsSNpmiyg9V6A7nKGxyU='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-WKFc+4eT4QW4fWj0egeZ3gCD0WV8CEUmYjqf5+sWJ6U=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-M550Mcnq31efgXZ8tIP36xvYBvbEUZGPoI9YuPY9stc='), or a nonce ('nonce-...') is required to enable inline execution.
```


/AMW_web/pages/settings.xhtml?mode=releases -> delete:
```        
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-mWzdt9KWvcmQzQn9Q//7CyfyMZr0TkkCh09E/Q8tDyI=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-8nwa44iHYG1PEysokyUQh2jl6UQbIuhAeJHCSpLu718='), or a nonce ('nonce-...') is required to enable inline execution.
```

/AMW_web/pages/settings.xhtml?mode=STP -> Add new STP -> Add Argument:
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-QtxPNSWhfwfmFPRjKhDoq5sGpruNRqTmaEq4XQ4IVH0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-SAiZe1Quc24R2IvgvkuFKe39/oNwvq8+WjGRquybw7I='), or a nonce ('nonce-...') is required to enable inline execution.
```
/AMW_web/pages/settings.xhtml?mode=STP -> Delete
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-QtxPNSWhfwfmFPRjKhDoq5sGpruNRqTmaEq4XQ4IVH0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Rusd+h88vD+Y3E7SI9xgcvK41z5KAAJTBj6fW4TMFDs='), or a nonce ('nonce-...') is required to enable inline execution.
```

AMW_web/pages/editResourceView.xhtml -> Add Relation -> Add as consumed Resource
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-+G5rq+uRS7jFQup2V8ra267WuVEE7fiGPrpn9s341DY='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-vX19F7XAGZdLtSSsvaXW3QdSClc9BR0jP55ZZS9bxg8='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-+G5rq+uRS7jFQup2V8ra267WuVEE7fiGPrpn9s341DY='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-KRlhyvrE5yF+tXnlEqz1ECBPM8e+66AhlKwOBKtdSyk='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-jAIShs+aebPgzXxQm03ZKEkn5YbdoJ7FhPBQIxsH5DM='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-XNkJJhRY0qckApEItuvycWmj91RFxiWxWwThYajFD1o='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-E7HkouQbpK23FI3ojoDkld7aIF9L0SUmHkeH9pACJRQ='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-tTtyrQHkSnLOXAzcx1vvkhBDaWzbDy09yL/P9oqiMwY='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-jBGVj/HwEr0RhM7q8hc8s/l39VwkPSG4JRCaIZpwM+w='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-yiobaIMnA/ibAM1TTyAn/HOPuXgKpOBCtsRnOR3FdAg='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-i9aS9wZp0rNixKkz/N00kDM8x2j0jqWFWhwqonAiIC0=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Lj3OZtoGQ8CliFDXBfA2tDNIMgLeI9h9sMcElbiahLg='), or a nonce ('nonce-...') is required to enable inline execution.
```

AMW_web/pages/editResourceView.xhtml -> Add Relation -> Add as consumed Resource, with a resource that is older than the main resource
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-vbtKfuDhmsVjMr+xbtMLTf4r4vBvW+Sj8vc9Xb7TFqA=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-+G5rq+uRS7jFQup2V8ra267WuVEE7fiGPrpn9s341DY='), or a nonce ('nonce-...') is required to enable inline execution.
```

AMW_web/pages/editResourceView.xhtml -> Click on a exclamation mark of a property
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-H6N6jFEk4Gux6zhedd1719qX27fQqOcqmdrjSB9kWVE=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-Yx0sKQq6nVG5OgIm+UvZ4dRK1MDW+VtSLfWy3vmgVbY='), or a nonce ('nonce-...') is required to enable inline execution.
```

AMW_web/pages/editResourceView.xhtml -> New Property Descriptor -> Change Property type
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-zYhK2Jh2VLWvV12JSkDgfjTPAHiXlojDECgmWXC8PwQ=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-0mTR0Y68h32d3HoIdnb/KGi1XfPhjlerAqKwKXO2glc='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-zYhK2Jh2VLWvV12JSkDgfjTPAHiXlojDECgmWXC8PwQ=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-ENEAKd1niTMmbvXyH3sD1pING5jlOwTJQxqI8bC32C8='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-zYhK2Jh2VLWvV12JSkDgfjTPAHiXlojDECgmWXC8PwQ=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-0mTR0Y68h32d3HoIdnb/KGi1XfPhjlerAqKwKXO2glc='), or a nonce ('nonce-...') is required to enable inline execution.
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-zYhK2Jh2VLWvV12JSkDgfjTPAHiXlojDECgmWXC8PwQ=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-qZJ7LLaP+NIa4FT0viZzXCyh97N3JiB7x22fmf38azM='), or a nonce ('nonce-...') is required to enable inline execution.
```

AMW_web/pages/editResourceView.xhtml -> Release -> Remove:
```
[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-EeZu8Pxhw/+fC3jE3wtjgrWLMme0G55MwC6L2aEQntk=' 'sha256-56Xl7F05vDGrlZ0zsrpH5ur8snvD2VXeGJW6hJvvbxU=' 'sha256-JnUQNzIwUQpUTIqGq+F8FFSf1//vhdKJyY/8LSNVWh0=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-XfcGlABfVMKkITxnqAzmEtf9+dERDBxnJ6OmNCz4RKI='), or a nonce ('nonce-...') is required to enable inline execution.
```



Could we also add `object-src 'none'`? It's recommended when pasting the CSP header here: https://csp-evaluator.withgoogle.com/

`base-uri` isn't set but recommended in the report. Why is that?

**Comment by StephGit** [comment]
CSP-Policy is updated and should not block scripts loaded from pop-ups. 
- added object-src 'none' and base-uri 'self'  

( `base-uri` not set at all  means allow any URL,  with `none` the requirements of the report are fulfilled.)

**Comment by yvespp** [comment]
I retested and it looks good to me. Can you please enforce the CSP and rebase?

**Comment by StephGit** [comment]
> Currently the rest API and the swagger UI (/AMW_rest) don't set any headers, should that be changed?

I will check that...

**Comment by StephGit** [comment]
Added CSP for swagger-ui and removed the Report-Only mode

**Review by yvespp — APPROVED** [review]

**Pull request merged**
